config(npm): heroku needs @types/node as regular dependency
see: https://stackoverflow.com/a/40365667

Error was: src/index.ts(1,1): error TS2304: Cannot find name 'require'.